### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by thehighestend** [Capturtle/ridi-decrypt#1]
Although the output claims all conversions were successful and "FAIL total: 0", nothing in DRM-REMOVED directory is recognised by the viewers(Adobe Acrobat, Calibre etc.).
The decrypted files are highly likely corrupt in that the readers say the files are possibly damaged.
I suggest you test with the most recent version of official RIDI viewer.

**Comment by Capturtle** [comment]
The current code does not verify if the decrypted file is a valid epub (or jpg) or not. It simply runs AES decryption, trusting user input. Also the RIDI viewer has not been updated since 2022 (v0.10.2), hence the encrypt/decrypt algorithm should stay the same. 

I suggest double checking the device id from: https://account.ridibooks.com/api/user-devices/app
Since the json can contain up to 5 device ids, you want to make sure you choose the correct one.

**Comment by thehighestend** [comment]
Looked into the json again and found another device entry with more recent timestamp.
Tried with it again and worked like a charm this time.
Now that this issue seems obviously resolved, I'll close this issue. Thanks for the tip.
